import numpy as np
import plotData as pD

# training set
# populationProfit.txt simulates the profits generated by a food truck company in different cities
# loading data from populationProfit.txt : first column, population, second column, profits
from matplotlib.pyplot import pause



popProfitData = np.genfromtxt("populationProfit.txt", dtype=float, delimiter=',')
populationColumn = popProfitData[:,0]
profitColumn = popProfitData[:,1]

# number of training set examples
m = profitColumn.size
# print("number of training set examples = ",profitColumn.size)

pD.plotData(populationColumn, profitColumn)
